- name: Deploy student app in DEV
  hosts: all
  become: yes
  vars:
    URL: URL-LOC
  tasks:
    - name: Remove the old war files
      file:
        name: "/root/apache-tomcat-9.0.16/webapps/{{item}}"
        state: absent
      with_items:
        - "{{item}}.war"
    - name: Download war file
      get_url:
        url: "{{URL}}"
        dest: /root/apache-tomcat-9.0.16/webapps/
